NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-20054-ca-westernrldc.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-20054-ca-westernrldc.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-20054-ca-westernrldc.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-20054-ca-westernrldc.pem
    OrganizationalUnitIdentifier: orderer
