# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # MUL
  # ---------------------------------------------------------------------------
  - Name: MUL
    Domain: mul.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # AEML
  # ---------------------------------------------------------------------------
  - Name: AEML
    Domain: aeml.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # ADANI BITTA
  # ---------------------------------------------------------------------------
  - Name: ADANIBITTA
    Domain: adanibitta.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # ADANI KAWAI
  # ---------------------------------------------------------------------------
  - Name: ADANIKAWAI
    Domain: adanikawai.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # ADANI TIRODA
  # ---------------------------------------------------------------------------
  - Name: ADANITIRODA
    Domain: adanitiroda.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # ADANI MUNDRA
  # ---------------------------------------------------------------------------
  - Name: ADANIMUNDRA
    Domain: adanimundra.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # GETCO
  # ---------------------------------------------------------------------------
  - Name: GETCO
    Domain: getco.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # RRVPNL
  # ---------------------------------------------------------------------------
  - Name: RRVPNL
    Domain: rrvpnl.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # PGCIL
  # ---------------------------------------------------------------------------
  - Name: PGCIL
    Domain: pgcil.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
# ---------------------------------------------------------------------------
  # MSETCL
  # ---------------------------------------------------------------------------
  - Name: MSETCL
    Domain: msetcl.mpower.in
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    Users:
      Count: 1